name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12', '3.13', '3.14']

        include:
          - os: ubuntu-latest
            python-version: '3.14'
            #nightly-numpy: true
            pack-nupkg: true

    runs-on: ${{ matrix.os }}
    name: Build - ${{ matrix.os }} - Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: true

      - name: Install packages
        shell: bash
        run: |
          python -m pip install --upgrade pip
          #if [ "${{ matrix.nightly-numpy || ''}}" = "true" ]; then
          #  #python -m pip install meson ninja cython
          #  #python -m pip install numpy --no-binary :all:
          #  python -m pip install --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy
          #else
          #  python -m pip install numpy
          #fi

          # Install polars-lts-cpu for non AVX2 environments,
          # which is more widely compatible and sufficient for our test suite. AVX2 builds are available but require more complex setup and have limited availability on CI runners.
          python -m pip install numpy pandas polars-lts-cpu pyarrow

      - name: Build
        shell: bash
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Test
        shell: bash
        run: |
          dotnet test -c Release --no-build --no-restore

      - name: Pack 
        if: matrix.pack-nupkg == true
        shell: bash
        run: |
          dotnet pack -c Release --no-build --no-restore -o nupkgs

      - name: Upload NuGet packages
        if: matrix.pack-nupkg == true
        uses: actions/upload-artifact@v7
        with:
          name: nuget-packages
          path: |
            nupkgs/*.nupkg
